header:
  - title: Features
    base: features
  - title: Learn
    base: learn
  - title: Download
    base: download
  - title: Documentation
    base: documentation

learn:
  - url: getting-started
    subs:
      - url: installation
      - url: hello-world
      - url: commands
  - url: test

exclude:
  - CNAME
  - LICENSE
  - README.md