header:
  - name: Features
    base: features
  - name: Learn
    base: learn
  - name: Documentation
    base: documentation
  - name: Packages
    base: packages

learn:
  - name: Introduction
    url: introduction
  - name: Getting Started
    url: getting-started
    subs:
      - name: First program
        url: first-program
      - name: Packages
        url: packages
  - name: Commands
    url: commands

exclude:
  - CNAME
  - LICENSE
  - README.md