header:
  - name: Features
    base: features
  - name: Learn
    base: learn
  - name: Documentation
    base: documentation
  - name: Packages
    base: packages

learn:
  - name: Getting Started
    url: getting-started
    subs:
      - name: Installation
        url: installation
      - name: Hello World
        url: hello-world
      - name: Commands
        url: commands

exclude:
  - CNAME
  - LICENSE
  - README.md