navigation:
  - title: Features
    base: features
  - title: Learn
    base: learn
  - title: Download
    base: download
  - title: Documentation
    base: documentation

exclude:
  - CNAME
  - LICENSE
  - README.md