learn:
  - name: Introduction
    url: introduction
  - name: Getting Started
    url: getting-started
    subs:
      - name: First program
        url: first-program
      - name: Package manager
        url: package-manager
      - name: Build system
        url: build-system
  - name: Commands
    url: commands