header:
  - name: Features
    base: features
  - name: Learn
    base: learn
  - name: Download
    base: download
  - name: Documentation
    base: documentation

learn:
  - name: Getting Started
    url: getting-started
    subs:
      - name: Installation
        url: installation
      - name: Hello World
        url: hello-world
      - name: Commands
        url: commands
  - name: Test
    url: test

exclude:
  - CNAME
  - LICENSE
  - README.md